
#    https://www.baeldung.com/spring-properties-file-outside-jar

spring:
  config:
    import: file:config/mailConfig.yml, file:config/dbConfig.yml

  jpa:
    generate-ddl: false
    open-in-view: false


  freemarker:
    expose-request-attributes: true   # свойство, отвечающее за помещение _csrf токенов в контекст шаблонизатора


upload:
  path: /tmp/Test/uploads


