
spring:
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: postgres
    password: 123456
  jpa:
    generate-ddl: true
    open-in-view: false

  freemarker:
    expose-request-attributes: true   # свойство, отвечающее за помещение _csrf токенов в контекст шаблонизатора


upload:
  path: /tmp/Tect/uploads


