
spring:
  datasource:
    url: jdbc:postgresql://localhost/sweater
    username: postgres
    password: 123456
  jpa:
    generate-ddl: true
    open-in-view: false

  mustache:
    expose-request-attributes: true
